### ISSUE TITLE
Downfall IDs are not known to cobr.ai

### ISSUE THREAD

**Issue by plural** [muyjohno/cobra#103]
Hello!

I ran a store champ on March 23, 2019 with some of the exciting new Downfall cards legal.  We had one player using the new Mirrormorph ID, but cobr.ai didn't recognize it.

What is the process for getting new ids updated for cobr.ai?  Does that come from nrdb or is there some config here? I saw ids referenced for things like TOME import, but not a general data file for it.  Admittedly, I didn't look very hard.  :D

**Comment by plural** [comment]
also, cobr.ai is a delight to use.  Thanks!

**Comment by ghost** [comment]
I think this can be closed

**Comment by muyjohno** [comment]
Apologies for the slow reply: IDs are stored internally in Cobra for a couple of reasons, and updating them is a somewhat manual process which I need to run. I'll look into automating this in some way in the future. (The IDs in question have been updated by now of course.)
