### ISSUE TITLE
Add link to stream(s) to the Title of the Tournament

### ISSUE THREAD

**Issue by ghost** [muyjohno/cobra#105]
As you are often looking up a tournament on cobr.ai it would be wonderful if the link(s) to the stream(s) could be published. It makes it easier to provide the link and easier to find it for people following the tournament.
I would recommend to show it beside the Title so it's linked on which ever page of a tournament you are

**Comment by muyjohno** [comment]
Thanks for the suggestion. I've added this feature now, look forward to it soon. (Apologies for the slow pace of work!)
