### ISSUE TITLE
Add printable QR code for link to tourney page

### ISSUE THREAD

**Issue by dodgepong** [muyjohno/cobra#80]
If there were a page that could be printed with a QR code for each tournament, that would be a nice thing for TOs to post up around the tournament area so that people could easily snap a pic and go straight to the tournament page with pairings and standings without having to manually type in a short code.

**Comment by muyjohno** [comment]
Hey,

Sorry for the slow reply, I didn't see this issue had been raised!

There is in fact a printable QR page for each tournament, accessible by the TO and linked from the "Tournament" tab. (To be fair, I'm not sure if this requests predates the implementation.)

Thanks for the request,
Johno
